// Code generated by MockGen. DO NOT EDIT.
// Source: domain/service/session.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	model "github.com/sekky0905/nuxt-vue-go-chat/server/domain/model"
	repository "github.com/sekky0905/nuxt-vue-go-chat/server/domain/repository"
	reflect "reflect"
)

// MockSessionService is a mock of SessionService interface
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// NewSession mocks base method
func (m *MockSessionService) NewSession(userID uint32) *model.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", userID)
	ret0, _ := ret[0].(*model.Session)
	return ret0
}

// NewSession indicates an expected call of NewSession
func (mr *MockSessionServiceMockRecorder) NewSession(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockSessionService)(nil).NewSession), userID)
}

// SessionID mocks base method
func (m *MockSessionService) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID
func (mr *MockSessionServiceMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockSessionService)(nil).SessionID))
}

// IsAlreadyExistID mocks base method
func (m_2 *MockSessionService) IsAlreadyExistID(ctx context.Context, m repository.SQLManager, id string) (bool, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "IsAlreadyExistID", ctx, m, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAlreadyExistID indicates an expected call of IsAlreadyExistID
func (mr *MockSessionServiceMockRecorder) IsAlreadyExistID(ctx, m, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlreadyExistID", reflect.TypeOf((*MockSessionService)(nil).IsAlreadyExistID), ctx, m, id)
}
